## Import Libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow

## Load data

In [12]:
data = np.loadtxt('AppleStoreClearned.csv', delimiter = ',')

In [13]:
data

array([[-3.97004852, -2.51233638,  5.34632961, ...,  0.3298398 ,
        -0.49159048,  1.        ],
       [-1.19521719, -2.83925653,  3.66405876, ...,  0.86753008,
        -0.72280937,  1.        ],
       [-0.29202386, -1.35128199, -1.73842916, ..., -0.03803333,
         2.62163647,  0.        ],
       ...,
       [-2.6345153 , -2.13824672, -2.44046129, ...,  4.76385918,
        -1.33461139,  0.        ],
       [-4.00800374, -1.77933711,  2.36639697, ...,  0.21448838,
        -2.22971981,  1.        ],
       [ 0.27853965, -1.71550503,  0.12121725, ..., -0.77657147,
         1.59979646,  1.        ]])

##  declearing independent variable

In [24]:
d_input = data[:,1:-1]
d_input

array([[-2.51233638,  5.34632961, -1.01200871,  1.84490036,  0.3298398 ,
        -0.49159048],
       [-2.83925653,  3.66405876,  1.58823231,  0.8532858 ,  0.86753008,
        -0.72280937],
       [-1.35128199, -1.73842916, -0.34261593,  2.83863551, -0.03803333,
         2.62163647],
       ...,
       [-2.13824672, -2.44046129,  0.65722289,  2.19970859,  4.76385918,
        -1.33461139],
       [-1.77933711,  2.36639697, -0.20032937,  2.16143512,  0.21448838,
        -2.22971981],
       [-1.71550503,  0.12121725, -1.15407476,  1.2666774 , -0.77657147,
         1.59979646]])

## declearing dependent variable

In [25]:
d_terget = data[:,-1]
d_terget

array([1., 1., 0., ..., 0., 1., 1.])

## spliting data into test, train and validation

In [26]:
sample_count = data.shape[0]
train_sample_count = int(0.8*sample_count) 
validation_sample_count = int(0.1*sample_count)
test_sample_count = sample_count-train_sample_count-validation_sample_count

In [27]:
train_input = d_input[:train_sample_count]
train_terget = d_terget[:train_sample_count]

In [30]:
validation_input = d_input[train_sample_count:train_sample_count+validation_sample_count]
validation_terget = d_terget[train_sample_count:train_sample_count+validation_sample_count]

In [32]:
test_input = d_input[train_sample_count+validation_sample_count:]
test_terget = d_terget[train_sample_count+validation_sample_count:]

## saving the splited data 

In [34]:
np.savez('AppleStoreTrain', inputs = train_input, target = train_terget)
np.savez('AppleStoreTest', inputs = test_input, target = test_terget)
np.savez('AppleStoreValidation', inputs = validation_input, target = validation_terget)
